createOrReplace

	ref table FactGovernmentDebt

		measure 'Debt – Distance to 60% (pp)' = ```
				
				VAR d = [Debt – % of GDP (Latest Common)]
				RETURN IF ( ISBLANK(d), BLANK(), d - 0.60 )  -- positivt = över 60%
				
				```
			displayFolder: DAX-GovernmentDebt\KPI
			lineageTag: 5ac4d4f0-13fd-4d6f-ac1b-42aa20378916

			annotation PBI_FormatHint = {"isGeneralNumber":true}

