createOrReplace

	ref table FactGovernmentDebt

		measure 'Debt – % of GDP (At Date)' = ```
				
				VAR DebtAll =
				    SUM ( FactGovernmentDebt[Value] )       
				VAR GDPAll  =
				    [GDP – 4Q Sum (At Date)]         
				RETURN DIVIDE ( DebtAll, GDPAll )
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: DAX-GovernmentDebt\Base
			lineageTag: ac38c977-673b-45fb-9c4a-109d5a46554a

		measure 'Debt – Value (EOP)' =
				
				CALCULATE ( [Debt – Value (Quarterly)],
				    LASTNONBLANK ( DimDate[Date], [Debt – Value (Quarterly)] ) )
			formatString: 0
			displayFolder: DAX-GovernmentDebt\Base
			lineageTag: 8d2f4895-f1a1-4036-a258-628e9d3d9f04

		measure 'Debt – Value (Quarterly)' =
				
				SUM ( FactGovernmentDebt[Value] )
			formatString: 0
			displayFolder: DAX-GovernmentDebt\Base
			lineageTag: fee9db7f-f5e4-463f-a25a-f5a20217cdab

