table DimRegion
	lineageTag: 78ce817a-3c57-4b2a-afce-73badddd5ee6

	measure 'Regions – Selected (Count)' =
			
			COUNTROWS ( VALUES ( DimRegion[RegionSK] ) )
			// Hur många regioner är valda just nu
		formatString: 0
		displayFolder: DAX
		lineageTag: 741c35bf-f516-4224-a098-3ed1841afd00

	column RegionSK
		dataType: int64
		formatString: 0
		lineageTag: 62496da1-055c-4412-86b6-35e5eb66f580
		summarizeBy: none
		sourceColumn: RegionSK

		annotation SummarizationSetBy = Automatic

	column RegionAK
		dataType: string
		lineageTag: 97013237-a5ef-4b54-8e92-81f9ae810e2a
		dataCategory: Country
		summarizeBy: none
		sourceColumn: RegionAK

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: c3354a67-4494-48c1-948c-b031e2339de2
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 754eb624-4e58-4fd2-aa26-ad8c84925c47
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: d1e4b865-b4ca-4e90-a2f1-e0b0206c3fb6
			defaultHierarchy: LocalDateTable_94ee2490-3fdd-442e-9a11-75154767326e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 689aa355-734d-4451-a10d-680b607be5f3
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: f8b60a03-d746-421b-abcd-40f7582197d8
			defaultHierarchy: LocalDateTable_3b94ece3-2971-4eb9-b934-ff509b29a2dd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition DimRegion = m
		mode: import
		source =
				let
				    Source = Sql.Databases("127.0.0.1,1433"),
				    LIA_DW_Gold = Source{[Name="LIA_DW_Gold"]}[Data],
				    Dim_Region = LIA_DW_Gold{[Schema="Dim",Item="Region"]}[Data]
				in
				    Dim_Region

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

