table FactEmployment
	lineageTag: 71ec5e73-0cbd-40f6-8024-ee7a224a987d

	measure 'Labour Force (Safe)' = ```
			
			    [Employment – Persons (Safe)] + [Unemployment – Persons (Safe)]
			```
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: 43494504-d1af-4b7a-9a88-2ad28e342cdb

	measure 'Employment – Persons (Quarterly)' = SUM ( FactEmployment[Value])
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: 782685ec-1bc7-450f-9df0-2010c66331e9

	measure 'Employment – Persons (Monthly FwdFill)' =
			// Använder senaste kända kvartalsvärde för vald månadsaxel
			CALCULATE (
			    [Employment – Persons (Quarterly)],
			    LASTNONBLANK ( VALUES ( DimDate[Date] ), [Employment – Persons (Quarterly)] )
			)
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: b7c897f6-09e8-4458-9a99-b7bcdfb8d001

	measure 'Employment – Persons (EOP)' =
			// End-of-period baserat på vald period
			CALCULATE (
			    [Employment – Persons (Quarterly)],
			    LASTNONBLANK ( DimDate[Date], [Employment – Persons (Quarterly)])
			)
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: 9a5239f8-81f4-4b71-ad77-a731142e1b1e

	measure 'Employment – Persons (Safe)' =
			// En (1) månad vald → periodvärde; annars EOP
			IF (
			    HASONEVALUE ( DimDate[YearMonth] ),
			    [Employment – Persons (Monthly FwdFill)],
			    [Employment – Persons (EOP)]
			)
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: 4b31fd3a-a13c-402b-a2fc-9fa614b31199

	measure 'Employment – Rate % (LF, At Date)' =
			// Sysselsatta som andel av arbetskraften vid valt datum
			VAR cur   = [Employment – Persons (Monthly FwdFill)]
			VAR denom = [Labour Force (Safe)]
			RETURN DIVIDE ( cur, denom )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: DAX\Employment
		lineageTag: d9c7009b-31a4-4d98-aa4c-3b42dd9aae9c

	measure 'Employment – YoY Δ (Persons)' = ```
			
			VAR Prev = CALCULATE([Employment – Persons (Safe)], DATEADD(DimDate[Date], -1, YEAR))
			RETURN [Employment – Persons (Safe)] - Prev
			
			```
		formatString: 0
		displayFolder: DAX\Employment
		lineageTag: 9cf83a2f-8659-49ce-a2e0-210e120fdca8

	measure 'Employment – Rate % YoY Δ (pp)' = ```
			
			VAR Prev = CALCULATE([Employment – Persons (Safe)], DATEADD(DimDate[Date], -1, YEAR))
			RETURN DIVIDE([Employment – Persons (Safe)] - Prev, Prev)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: DAX\Employment
		lineageTag: 84822570-9ac7-4282-bcef-135d072ea1db

	column FactEmploymentKey
		dataType: int64
		formatString: 0
		lineageTag: 6ac3408e-116d-47bf-9349-3ea4e124d50c
		summarizeBy: count
		sourceColumn: FactEmploymentKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 25074a6b-96ad-42dc-b33e-7a89729c05f0
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column TimeFrequencyKey
		dataType: int64
		formatString: 0
		lineageTag: 766d4688-f6e1-426b-85cd-7271e1dedb0d
		summarizeBy: none
		sourceColumn: TimeFrequencyKey

		annotation SummarizationSetBy = Automatic

	column GenderKey
		dataType: int64
		formatString: 0
		lineageTag: b9112ebd-5684-4630-a1e9-c41b680b5e55
		summarizeBy: none
		sourceColumn: GenderKey

		annotation SummarizationSetBy = Automatic

	column RegionKey
		dataType: int64
		formatString: 0
		lineageTag: 39a7e5eb-4909-41ae-8f25-de44473f8770
		summarizeBy: none
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	column AgeClassKey
		dataType: int64
		formatString: 0
		lineageTag: a92b4cf5-c41a-409b-9594-d9c349f26502
		summarizeBy: none
		sourceColumn: AgeClassKey

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 5342bdc7-e1c8-4873-9932-b567ac285830
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column FlagKey
		dataType: int64
		formatString: 0
		lineageTag: f2cdd60e-57a7-4f8c-846b-b7130c1b6267
		summarizeBy: none
		sourceColumn: FlagKey

		annotation SummarizationSetBy = Automatic

	column CreatedGoldAt
		dataType: dateTime
		formatString: General Date
		lineageTag: f11c7e12-aa0d-45a0-8dae-c54ecd702493
		summarizeBy: none
		sourceColumn: CreatedGoldAt

		variation Variation
			isDefault
			relationship: 77a74d06-10dd-48ba-af79-b0d56994191a
			defaultHierarchy: LocalDateTable_fef5792c-b27d-4faa-a4d7-36aeac47b1c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FactEmployment = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    LIA_DW_Gold = Source{[Name="LIA_DW_Gold"]}[Data],
				    Fact_Employment = LIA_DW_Gold{[Schema="Fact",Item="Employment"]}[Data]
				in
				    Fact_Employment

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

