table FactUnemployment
	lineageTag: b23f7f6f-49f2-4df8-92d1-e6e165262b52

	measure 'Latest Date – Unemployment (PerEntity)' =
			
			VAR d =
			    CALCULATE (
			        MAX ( DimDate[Date] ),
			        FILTER (
			            ALLSELECTED ( DimDate[Date] ),
			            NOT ISBLANK ( [Unemployment – Persons (Monthly)])
			        )
			    )
			RETURN d
		formatString: General Date
		displayFolder: DAX\Unemployment
		lineageTag: 83d1e738-12c6-4a82-adcf-50ce2b165fde

	measure 'Latest Date Label – Unemployment' = FORMAT ( [Latest Date – Unemployment (PerEntity)], "yyyy-MM" )
		displayFolder: DAX\Unemployment
		lineageTag: f8b851cc-e7fc-45aa-aa38-ee9b41cd013f

	measure 'Unemployment – Persons (Monthly)' = SUM ( FactUnemployment[Value])
		formatString: 0
		displayFolder: DAX\Unemployment
		lineageTag: f764fb18-7a85-457d-a453-6dd634e8c204

	measure 'Unemployment – Persons (EOP)' =
			// Senaste månad i urvalet som har värde
			CALCULATE (
			    [Unemployment – Persons (Monthly)],
			    LASTNONBLANK ( DimDate[Date], [Unemployment – Persons (Monthly)] )
			)
		formatString: 0
		displayFolder: DAX\Unemployment
		lineageTag: 40ad8673-6112-4d64-a100-4ecc70fb8685

	measure 'Unemployment – Persons (Safe)' =
			// 1 månad vald → periodvärde; annars EOP
			IF (
			    HASONEVALUE ( DimDate[YearMonth] ),
			    [Unemployment – Persons (Monthly)],
			    [Unemployment – Persons (EOP)]
			)
		formatString: 0
		displayFolder: DAX\Unemployment
		lineageTag: 0b1252de-0f58-4c9f-b5fa-4bcbefc6ad6c

	measure 'Unemployment – Rate % (EOP)' = DIVIDE ( [Unemployment – Persons (EOP)], [Labour Force (Safe)] )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: DAX\Unemployment
		lineageTag: 0bf54095-f0e4-4414-86b1-c5b2d91aea49

	measure 'Unemployment – Rate % MoM Δ (pp)' =
			VAR Prev =
			    CALCULATE ( [Unemployment – Rate % (EOP)], DATEADD ( DimDate[Date], -1, MONTH ) )
			RETURN [Unemployment – Rate % (EOP)] - Prev
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: DAX\Unemployment
		lineageTag: 141d1857-bc50-4649-925c-3916da863be2

	measure 'Unemployment – Rate % YoY Δ (pp)' =
			VAR Prev =
			    CALCULATE ( [Unemployment – Rate % (EOP)], DATEADD ( DimDate[Date], -1, YEAR ) )
			RETURN [Unemployment – Rate % (EOP)] - Prev
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: DAX\Unemployment
		lineageTag: 70d211f5-c5c8-4ac6-91b3-1b017d3cf92a

	measure 'Unemployment – YoY Δ (Persons)' =
			
			VAR Prev = CALCULATE([Unemployment – Persons (Safe)], DATEADD(DimDate[Date], -1, YEAR))
			RETURN [Unemployment – Persons (Safe)] - Prev
		formatString: 0
		displayFolder: DAX\Unemployment
		lineageTag: 47328f13-6458-48f4-b384-68a92488450f

	measure 'LastDate – Unemp (Per Region)' =
			
			CALCULATE (
			    MAX ( DimDate[Date] ),
			    FILTER ( ALLSELECTED ( DimDate[Date] ), NOT ISBLANK ( [Unemployment – Rate % (EOP)] ) )
			)
			// UNEMP: senaste datum med värde (respekterar slicers)
		formatString: General Date
		displayFolder: DAX\Unemployment
		lineageTag: 21c8f19a-c144-44da-8b1d-cad59cec1157

	column FactUnemploymentKey
		dataType: int64
		formatString: 0
		lineageTag: 75796c3e-210b-437f-b9ff-40b5ed7478d9
		summarizeBy: count
		sourceColumn: FactUnemploymentKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 6567bf76-23a9-47ef-927d-1f262e11c08e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column TimeFrequencyKey
		dataType: int64
		formatString: 0
		lineageTag: f4cbf103-0e27-45eb-a704-f2153dce43ba
		summarizeBy: none
		sourceColumn: TimeFrequencyKey

		annotation SummarizationSetBy = Automatic

	column GenderKey
		dataType: int64
		formatString: 0
		lineageTag: 460e1324-28bd-4eb6-92cd-1f4dcefddba0
		summarizeBy: none
		sourceColumn: GenderKey

		annotation SummarizationSetBy = Automatic

	column RegionKey
		dataType: int64
		formatString: 0
		lineageTag: 07da87b8-e456-4f9e-a934-24a531b01642
		summarizeBy: none
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	column AgeClassKey
		dataType: int64
		formatString: 0
		lineageTag: f1bd305e-9f0b-44d0-8e53-37ed5da69a2a
		summarizeBy: none
		sourceColumn: AgeClassKey

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: f46a0316-b1dc-4dfd-bb79-4f7ccab9f301
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column FlagKey
		dataType: int64
		formatString: 0
		lineageTag: e9a81ed6-3448-4f61-9f7d-3d8560ea38df
		summarizeBy: none
		sourceColumn: FlagKey

		annotation SummarizationSetBy = Automatic

	column CreatedGoldAt
		dataType: dateTime
		formatString: General Date
		lineageTag: c502b151-ed9b-4a31-8143-ddf53f85d7b3
		summarizeBy: none
		sourceColumn: CreatedGoldAt

		variation Variation
			isDefault
			relationship: 53d4360c-6e6b-4ad0-b180-acc04e38ab77
			defaultHierarchy: LocalDateTable_0b7434a5-9b4c-40f9-a488-afe50b20876c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FactUnemployment = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    LIA_DW_Gold = Source{[Name="LIA_DW_Gold"]}[Data],
				    Fact_Unemployment = LIA_DW_Gold{[Schema="Fact",Item="Unemployment"]}[Data]
				in
				    Fact_Unemployment

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

